name: fuel_gage
description: "Fuel Gage - A simple calorie tracker that treats your body like a fuel tank."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.3.5

  # Utilities
  intl: ^0.20.1
  uuid: ^4.5.1

  # UI Components
  percent_indicator: ^4.2.3
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
